# Generated by Django 6.0.2 on 2026-02-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.URLField(blank=True, help_text='Please provide an URL for your profile picture', null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
