# Generated by Django 6.0.2 on 2026-02-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.URLField(blank=True, help_text='If you wish to add a profile pic for your profile, please add a link above.', null=True),
        ),
    ]
