# Generated by Django 6.0.2 on 2026-03-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='user',
            new_name='profile',
        ),
    ]
