# Generated by Django 6.0.2 on 2026-03-31 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_profile_pic'),
        ('quests', '0002_rename_user_quest_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='profiles.profile'),
        ),
    ]
