# Generated by Django 6.0.2 on 2026-02-17 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeastsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='HowToWin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_name', models.CharField(max_length=130)),
                ('my_notes', models.TextField()),
                ('level_of_danger', models.PositiveIntegerField()),
                ('image_url', models.URLField()),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.beastsgroup')),
                ('what_to_use', models.ManyToManyField(to='bestiary.howtowin')),
            ],
        ),
    ]
