# Generated by Django 6.0.2 on 2026-02-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0002_alter_monster_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='level_of_danger',
            field=models.PositiveIntegerField(choices=[(1, 'Easy'), (2, 'Normal'), (3, 'High'), (4, 'Extreme')]),
        ),
        migrations.AlterField(
            model_name='monster',
            name='monster_name',
            field=models.CharField(max_length=100),
        ),
    ]
