# Generated by Django 6.0.2 on 2026-02-19 18:05

import bestiary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0003_alter_monster_level_of_danger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monster_name',
            field=models.CharField(max_length=100, validators=[bestiary.models.validate_letters_and_spaces]),
        ),
    ]
