# Generated by Django 6.0.2 on 2026-02-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0004_alter_monster_monster_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='my_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
