# Generated by Django 6.0.2 on 2026-02-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0005_alter_monster_my_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='my_notes',
            field=models.TextField(default='No notes recorded yet.'),
            preserve_default=False,
        ),
    ]
