# Generated by Django 6.0.2 on 2026-02-20 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0006_alter_monster_my_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='bestiary.beastsgroup'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='what_to_use',
            field=models.ManyToManyField(related_name='monsters', to='bestiary.howtowin'),
        ),
    ]
