# Generated by Django 6.0.2 on 2026-03-31 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0007_alter_monster_kind_alter_monster_what_to_use'),
        ('profiles', '0003_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='hunter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='profiles.profile'),
            preserve_default=False,
        ),
    ]
