# Generated by Django 6.0.2 on 2026-04-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0008_monster_hunter'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/monsters/'),
        ),
    ]
