# Generated by Django 6.0.2 on 2026-04-01 18:08

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    apprentice_group, _ = Group.objects.get_or_create(name='Apprentice Hunter')
    master_group, _ = Group.objects.get_or_create(name='Master Witcher')

    #can view everything and add monsters
    apprentice_perms = [
        'view_monster', 'add_monster',
        'view_quest', 'view_weapon', 'view_profile'
    ]

    # full CRUD on game content
    master_perms = [
        'add_monster', 'change_monster', 'delete_monster', 'view_monster',
        'add_quest', 'change_quest', 'delete_quest', 'view_quest',
        'add_weapon', 'change_weapon', 'delete_weapon', 'view_weapon'
    ]

    def assign_perms(group, perms_list):
        for code in perms_list:
            try:
                perm = Permission.objects.get(codename=code)
                group.permissions.add(perm)
            except Permission.DoesNotExist:
                continue

    assign_perms(apprentice_group, apprentice_perms)
    assign_perms(master_group, master_perms)

class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]